version: 2.1

# Pipeline template
shared: &shared
    docker:
        - image: continuumio/miniconda3
          environment:
             BASH_ENV: ~/.bashrc
    working_directory: ~/pytest-monitor.ci
    steps:
        - checkout
        - run:
            name: "Setup Environment"
            command: |
                conda create -n ci ${CI_PYTHON} -c https://conda.anaconda.org/conda-forge -c defaults -c anaconda -y
                conda install -n ci ${CI_PYTEST} -c https://conda.anaconda.org/conda-forge -c defaults -c anaconda -y
                conda install -n ci --file requirements.txt -c https://conda.anaconda.org/conda-forge -c defaults -c anaconda -y
                conda init bash
        - run:
            name: "Prepare Project"
            command: |
                conda activate ci
                python setup.py develop
        - run:
            name: "Testing"
            command: |
                conda init bash
                conda activate ci
                mkdir test-results
                pytest --junit-xml=test-results/junit.xml -s
        - store_test_results:
            path: test-results
        - store_artifacts:
            path: test-results

# Workflow definition
workflows:
    standard:
        jobs:
            - pytestmonitor-py36-pytest44:
                filters:
                    tags:
                        only: /.*/
            - pytestmonitor-py36-pytest45:
                filters:
                    tags:
                        only: /.*/
            - pytestmonitor-py36-pytest46:
                filters:
                    tags:
                        only: /.*/
            - pytestmonitor-py36-pytest50:
                filters:
                    tags:
                        only: /.*/
            - pytestmonitor-py36-pytest51:
                filters:
                    tags:
                        only: /.*/
            - pytestmonitor-py36-pytest52:
                filters:
                    tags:
                        only: /.*/
            - pytestmonitor-py36-pytest53:
                filters:
                    tags:
                        only: /.*/
            - pytestmonitor-py36-pytest54:
                  filters:
                      tags:
                          only: /.*/
            - pytestmonitor-py36-pytest60:
                  filters:
                      tags:
                          only: /.*/
            - pytestmonitor-py36-pytest61:
                  filters:
                      tags:
                          only: /.*/
            - pytestmonitor-py37-pytest44:
                filters:
                    tags:
                        only: /.*/
            - pytestmonitor-py37-pytest45:
                filters:
                    tags:
                        only: /.*/
            - pytestmonitor-py37-pytest46:
                filters:
                    tags:
                        only: /.*/
            - pytestmonitor-py37-pytest50:
                filters:
                    tags:
                        only: /.*/
            - pytestmonitor-py37-pytest51:
                filters:
                    tags:
                        only: /.*/
            - pytestmonitor-py37-pytest52:
                filters:
                    tags:
                        only: /.*/
            - pytestmonitor-py37-pytest53:
                filters:
                    tags:
                        only: /.*/
            - pytestmonitor-py37-pytest54:
                  filters:
                      tags:
                          only: /.*/
            - pytestmonitor-py37-pytest60:
                  filters:
                      tags:
                          only: /.*/
            - pytestmonitor-py37-pytest61:
                  filters:
                      tags:
                          only: /.*/
            - pytestmonitor-py38-pytest46:
                filters:
                    tags:
                        only: /.*/
            - pytestmonitor-py38-pytest52:
                filters:
                    tags:
                        only: /.*/
            - pytestmonitor-py38-pytest53:
              filters:
                  tags:
                      only: /.*/
            - pytestmonitor-py38-pytest54:
                  filters:
                      tags:
                          only: /.*/
            - pytestmonitor-py38-pytest60:
                  filters:
                      tags:
                          only: /.*/
            - pytestmonitor-py38-pytest61:
                  filters:
                      tags:
                          only: /.*/
            - deploy:
                requires:
                    - pytestmonitor-py36-pytest44
                    - pytestmonitor-py36-pytest45
                    - pytestmonitor-py36-pytest46
                    - pytestmonitor-py36-pytest50
                    - pytestmonitor-py36-pytest51
                    - pytestmonitor-py36-pytest52
                    - pytestmonitor-py36-pytest53
                    - pytestmonitor-py36-pytest54
                    - pytestmonitor-py36-pytest60
                    - pytestmonitor-py36-pytest61
                    - pytestmonitor-py37-pytest44
                    - pytestmonitor-py37-pytest45
                    - pytestmonitor-py37-pytest46
                    - pytestmonitor-py37-pytest50
                    - pytestmonitor-py37-pytest51
                    - pytestmonitor-py37-pytest52
                    - pytestmonitor-py37-pytest53
                    - pytestmonitor-py37-pytest54
                    - pytestmonitor-py37-pytest60
                    - pytestmonitor-py37-pytest61
                    - pytestmonitor-py38-pytest46
                    - pytestmonitor-py38-pytest52
                    - pytestmonitor-py38-pytest53
                    - pytestmonitor-py38-pytest54
                    - pytestmonitor-py38-pytest60
                    - pytestmonitor-py38-pytest61
                filters:
                    tags:
                        only: /^[a-zA-Z].*/
                    branches:
                        ignore: /.*/
    nightly:
        triggers:
            - schedule:
                cron: "0 0 * * *"
                filters:
                    branches:
                        only:
                            - master
        jobs:
            - nightly_build

# Jobs definition
jobs:
    pytestmonitor-py36-pytest44:
        environment:
            CI_PYTHON: 'python=3.6'
            CI_PYTEST: 'pytest=4.4'
        <<: *shared
    pytestmonitor-py36-pytest45:
        environment:
            CI_PYTHON: 'python=3.6'
            CI_PYTEST: 'pytest=4.5'
        <<: *shared
    pytestmonitor-py36-pytest46:
        environment:
            CI_PYTHON: 'python=3.6'
            CI_PYTEST: 'pytest=4.6'
        <<: *shared
    pytestmonitor-py36-pytest50:
        environment:
            CI_PYTHON: 'python=3.6'
            CI_PYTEST: 'pytest=5.0'
        <<: *shared
    pytestmonitor-py36-pytest51:
        environment:
            CI_PYTHON: 'python=3.6'
            CI_PYTEST: 'pytest=5.1'
        <<: *shared
    pytestmonitor-py36-pytest52:
        environment:
            CI_PYTHON: 'python=3.6'
            CI_PYTEST: 'pytest=5.2'
        <<: *shared
    pytestmonitor-py36-pytest53:
        environment:
            CI_PYTHON: 'python=3.6'
            CI_PYTEST: 'pytest=5.3'
        <<: *shared
    pytestmonitor-py36-pytest54:
        environment:
            CI_PYTHON: 'python=3.6'
            CI_PYTEST: 'pytest=5.4'
        <<: *shared
    pytestmonitor-py36-pytest60:
        environment:
            CI_PYTHON: 'python=3.6'
            CI_PYTEST: 'pytest=6.0'
        <<: *shared
    pytestmonitor-py36-pytest61:
        environment:
            CI_PYTHON: 'python=3.6'
            CI_PYTEST: 'pytest=6.1'
        <<: *shared
    pytestmonitor-py37-pytest44:
        environment:
            CI_PYTHON: 'python=3.7'
            CI_PYTEST: 'pytest=4.4'
        <<: *shared
    pytestmonitor-py37-pytest45:
        environment:
            CI_PYTHON: 'python=3.7'
            CI_PYTEST: 'pytest=4.5'
        <<: *shared
    pytestmonitor-py37-pytest46:
        environment:
            CI_PYTHON: 'python=3.7'
            CI_PYTEST: 'pytest=4.6'
        <<: *shared
    pytestmonitor-py37-pytest50:
        environment:
            CI_PYTHON: 'python=3.7'
            CI_PYTEST: 'pytest=5.0'
        <<: *shared
    pytestmonitor-py37-pytest51:
        environment:
            CI_PYTHON: 'python=3.7'
            CI_PYTEST: 'pytest=5.1'
        <<: *shared
    pytestmonitor-py37-pytest52:
        environment:
            CI_PYTHON: 'python=3.7'
            CI_PYTEST: 'pytest=5.2'
        <<: *shared
    pytestmonitor-py37-pytest53:
        environment:
            CI_PYTHON: 'python=3.7'
            CI_PYTEST: 'pytest=5.3'
        <<: *shared
    pytestmonitor-py37-pytest54:
        environment:
            CI_PYTHON: 'python=3.7'
            CI_PYTEST: 'pytest=5.4'
        <<: *shared
    pytestmonitor-py37-pytest60:
        environment:
            CI_PYTHON: 'python=3.7'
            CI_PYTEST: 'pytest=6.0'
        <<: *shared
    pytestmonitor-py37-pytest61:
        environment:
            CI_PYTHON: 'python=3.7'
            CI_PYTEST: 'pytest=6.1'
        <<: *shared
    pytestmonitor-py38-pytest46:
        environment:
            CI_PYTHON: 'python=3.8'
            CI_PYTEST: 'pytest=4.6'
        <<: *shared
    pytestmonitor-py38-pytest52:
        environment:
            CI_PYTHON: 'python=3.8'
            CI_PYTEST: 'pytest=5.2'
        <<: *shared
    pytestmonitor-py38-pytest53:
        environment:
            CI_PYTHON: 'python=3.8'
            CI_PYTEST: 'pytest=5.3'
        <<: *shared
    pytestmonitor-py38-pytest54:
        environment:
            CI_PYTHON: 'python=3.8'
            CI_PYTEST: 'pytest=5.4'
        <<: *shared
    pytestmonitor-py38-pytest60:
        environment:
            CI_PYTHON: 'python=3.8'
            CI_PYTEST: 'pytest=6.0'
        <<: *shared
    pytestmonitor-py38-pytest61:
        environment:
            CI_PYTHON: 'python=3.8'
            CI_PYTEST: 'pytest=6.1'
        <<: *shared
    nightly_build:
        environment:
            CI_PYTHON: 'python'
            CI_PYTEST: 'pytest'
        <<: *shared
    deploy:
        docker:
            - image: continuumio/miniconda3
              environment:
                BASH_ENV: ~/.bashrc
        working_directory: ~/pytest-monitor.ci
        steps:
            - checkout
            - run:
                name: "Prepare for deployment"
                command: |
                    conda create -n ci python=3.8 twine wheel setuptools -c https://conda.anaconda.org/conda-forge -c defaults -c anaconda -y
                    conda init bash
                    echo -e "[pypi]" >> ~/.pypirc
                    echo -e "username = __token__" >> ~/.pypirc
                    echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc

            - run:
                name: "Package Project"
                command: |
                    conda activate ci
                    python setup.py sdist bdist_wheel
            - run:
                name: "Publish"
                command: |
                    conda init bash
                    conda activate ci
                    twine upload dist/*
